# Случайное блуждание

__Автор задач: Блохин Н.В. (NVBlokhin@fa.ru)__

Материалы:
* Макрушин С.В. "Лекция 5: Случайные блуждания на графах"
* Документация:
    * https://networkx.org/documentation/stable/reference/generated/networkx.generators.social.karate_club_graph.html
    * https://numpy.org/doc/stable/reference/generated/numpy.diag.html
    * https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html
    * https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_power.html
    * https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

## Вопросы для совместного обсуждения

1\. Обсудите понятие случайного блуждания на графах.

In [1]:
import networkx as nx

In [2]:
G = nx.karate_club_graph()

In [3]:
G.edges(data="weight")

EdgeDataView([(0, 1, 4), (0, 2, 5), (0, 3, 3), (0, 4, 3), (0, 5, 3), (0, 6, 3), (0, 7, 2), (0, 8, 2), (0, 10, 2), (0, 11, 3), (0, 12, 1), (0, 13, 3), (0, 17, 2), (0, 19, 2), (0, 21, 2), (0, 31, 2), (1, 2, 6), (1, 3, 3), (1, 7, 4), (1, 13, 5), (1, 17, 1), (1, 19, 2), (1, 21, 2), (1, 30, 2), (2, 3, 3), (2, 7, 4), (2, 8, 5), (2, 9, 1), (2, 13, 3), (2, 27, 2), (2, 28, 2), (2, 32, 2), (3, 7, 3), (3, 12, 3), (3, 13, 3), (4, 6, 2), (4, 10, 3), (5, 6, 5), (5, 10, 3), (5, 16, 3), (6, 16, 3), (8, 30, 3), (8, 32, 3), (8, 33, 4), (9, 33, 2), (13, 33, 3), (14, 32, 3), (14, 33, 2), (15, 32, 3), (15, 33, 4), (18, 32, 1), (18, 33, 2), (19, 33, 1), (20, 32, 3), (20, 33, 1), (22, 32, 2), (22, 33, 3), (23, 25, 5), (23, 27, 4), (23, 29, 3), (23, 32, 5), (23, 33, 4), (24, 25, 2), (24, 27, 3), (24, 31, 2), (25, 31, 7), (26, 29, 4), (26, 33, 2), (27, 33, 4), (28, 31, 2), (28, 33, 2), (29, 32, 4), (29, 33, 2), (30, 32, 3), (30, 33, 3), (31, 32, 4), (31, 33, 4), (32, 33, 5)])

In [4]:
A = nx.adjacency_matrix(G, weight=None).toarray()
A

C:\Users\Elena\AppData\Local\Temp\ipykernel_5032\413398527.py:1: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  A = nx.adjacency_matrix(G, weight=None).toarray()


array([[0, 1, 1, ..., 1, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 1, 1, 0]], dtype=int32)

In [5]:
A[0] / A[0].sum()

array([0.    , 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625,
       0.0625, 0.    , 0.0625, 0.0625, 0.0625, 0.0625, 0.    , 0.    ,
       0.    , 0.0625, 0.    , 0.0625, 0.    , 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.0625,
       0.    , 0.    ])

In [6]:
import numpy as np

D = np.diag([1, 2, 3, 4])
D

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Задачи для самостоятельного решения

<p class="task" id="1"></p>

1\. Загрузите граф карате-клуба. Получите матрицу смежности `A` этого графа. Получите на ее основе матрицу переходов `P` по следующему правилу:

$$\mathbf{P}=\mathbf{D}^{-1}\mathbf{A}$$

Продемонстрируйте, что выполняются условия (1) и (2).

$0 \le p_{ij} \le 1$ (1)

$\sum_j p_{ij}=1$    (2)

- [ ] Проверено на семинаре

In [7]:
import networkx as nx
import pandas as pd
import numpy as np

In [8]:
G = nx.karate_club_graph()

In [9]:
A = nx.adjacency_matrix(G, weight='None').toarray()

C:\Users\Elena\AppData\Local\Temp\ipykernel_5032\3486741755.py:1: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  A = nx.adjacency_matrix(G, weight='None').toarray()


In [10]:
D = np.diag(A.sum(axis=1))
D

array([[16,  0,  0, ...,  0,  0,  0],
       [ 0,  9,  0, ...,  0,  0,  0],
       [ 0,  0, 10, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  6,  0,  0],
       [ 0,  0,  0, ...,  0, 12,  0],
       [ 0,  0,  0, ...,  0,  0, 17]], dtype=int32)

In [11]:
D = np.diag(list(dict(G.degree()).values()))
D

array([[16,  0,  0, ...,  0,  0,  0],
       [ 0,  9,  0, ...,  0,  0,  0],
       [ 0,  0, 10, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  6,  0,  0],
       [ 0,  0,  0, ...,  0, 12,  0],
       [ 0,  0,  0, ...,  0,  0, 17]])

In [12]:
P = np.linalg.inv(D) @ A
P

array([[0.        , 0.0625    , 0.0625    , ..., 0.0625    , 0.        ,
        0.        ],
       [0.11111111, 0.        , 0.11111111, ..., 0.        , 0.        ,
        0.        ],
       [0.1       , 0.1       , 0.        , ..., 0.        , 0.1       ,
        0.        ],
       ...,
       [0.16666667, 0.        , 0.        , ..., 0.        , 0.16666667,
        0.16666667],
       [0.        , 0.        , 0.08333333, ..., 0.08333333, 0.        ,
        0.08333333],
       [0.        , 0.        , 0.        , ..., 0.05882353, 0.05882353,
        0.        ]])

In [13]:
np.all(P >= 0), np.all(P <= 1)

(True, True)

In [14]:
np.sum(P, axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<p class="task" id="2"></p>

2\. Создайте вектор начального состояния $\mathbf{p}^0 = [0, ..., 1]^T$. Получите стационарное состояние $\mathbf{p}^\infty$, используя итеративную процедуру

$\mathbf{p}^{t+1}=(\mathbf{P}^{\top})\mathbf{p}^t$

Процесс заканчивается, когда $||\mathbf{p}^{t+1} - \mathbf{p}^{t}|| < \epsilon $

Выведите полученный вектор стационарного состояния на экран.

- [ ] Проверено на семинаре

In [15]:
p_0 = 34*[0]
print(p_0)
p_0[-1]=1
print(p_0)
p_0 = np.array(p_0)
print(p_0)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [16]:
p_i = p_0
p_next= (P.T) @ p_0
eps=0.001
while np.linalg.norm(p_next - p_i) > eps:
    p_next = (P.T) @ p_i
    p_i=p_next   

In [17]:
print(p_next)

[0.         0.         0.         0.         0.         0.
 0.         0.         0.05882353 0.05882353 0.         0.
 0.         0.05882353 0.05882353 0.05882353 0.         0.
 0.05882353 0.05882353 0.05882353 0.         0.05882353 0.05882353
 0.         0.         0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.        ]


<p class="task" id="3"></p>

3\. Найдите матрицу перехода к стационарному состоянию $(\mathbf{P}^{\top})^\infty$ при помощи процедуры возведения матрицы в степень.

Докажите, что полученная матрица является матрицей стационарного состояния, т.е. $||(\mathbf{P}^{\top})^{\infty}  -(\mathbf{P}^{\top})(\mathbf{P}^{\top})^{\infty}|| <= \epsilon$

Выведите полученную матрицу на экран.

- [ ] Проверено на семинаре

In [18]:
eps=0.00001
i=1
while np.linalg.norm(np.linalg.matrix_power(P.T, i) - (P.T)@np.linalg.matrix_power(P.T, i))>=eps:
    P=np.linalg.matrix_power(P.T, i)
    i+=1

In [19]:
np.linalg.norm(np.linalg.matrix_power(P.T, 100) - (P.T)@np.linalg.matrix_power(P.T, 100)) <= eps

True

In [20]:
P_inf=np.linalg.matrix_power(P.T, 100)
P_inf

array([[0.1025641 , 0.1025641 , 0.1025641 , ..., 0.1025641 , 0.1025641 ,
        0.1025641 ],
       [0.05769231, 0.05769231, 0.05769231, ..., 0.05769231, 0.05769231,
        0.05769231],
       [0.06410256, 0.06410256, 0.06410256, ..., 0.06410256, 0.06410256,
        0.06410256],
       ...,
       [0.03846154, 0.03846154, 0.03846154, ..., 0.03846154, 0.03846154,
        0.03846154],
       [0.07692308, 0.07692308, 0.07692308, ..., 0.07692308, 0.07692308,
        0.07692308],
       [0.10897436, 0.10897436, 0.10897436, ..., 0.10897436, 0.10897436,
        0.10897436]])

<p class="task" id="4"></p>

4\. Cоздайте вектор начального состояния $\mathbf{p}^0 = [0, ..., 1]^T $. Получите стационарное состояние $\mathbf{p}^\infty$, воспользовавшись полученной матрицей $(\mathbf{P}^{\top})^\infty$. Решите задачу двумя способами: при помощи матричного умножения и при помощи оператора индексации.

Используя функцию `np.allclose`, покажите, что векторы стационарных состояний, полученные двумя разными методами, совпадают (с точностью до тысячных).

- [ ] Проверено на семинаре

In [21]:
p_0 = 34*[0]
p_0[-1]=1
p_0 = np.array(p_0)

In [22]:
p_i = p_0
p_next= (P.T) @ p_0
eps=0.001

In [23]:
# способ 1
p_inf_41 = P_inf.T @ p_0
p_inf_41

array([0.10897436, 0.10897436, 0.10897436, 0.10897436, 0.10897436,
       0.10897436, 0.10897436, 0.10897436, 0.10897436, 0.10897436,
       0.10897436, 0.10897436, 0.10897436, 0.10897436, 0.10897436,
       0.10897436, 0.10897436, 0.10897436, 0.10897436, 0.10897436,
       0.10897436, 0.10897436, 0.10897436, 0.10897436, 0.10897436,
       0.10897436, 0.10897436, 0.10897436, 0.10897436, 0.10897436,
       0.10897436, 0.10897436, 0.10897436, 0.10897436])

In [34]:
# способ 2
p_inf_42 = P_inf.T[:, -1]
p_inf_42

array([0.10897436, 0.10897436, 0.10897436, 0.10897436, 0.10897436,
       0.10897436, 0.10897436, 0.10897436, 0.10897436, 0.10897436,
       0.10897436, 0.10897436, 0.10897436, 0.10897436, 0.10897436,
       0.10897436, 0.10897436, 0.10897436, 0.10897436, 0.10897436,
       0.10897436, 0.10897436, 0.10897436, 0.10897436, 0.10897436,
       0.10897436, 0.10897436, 0.10897436, 0.10897436, 0.10897436,
       0.10897436, 0.10897436, 0.10897436, 0.10897436])

In [35]:
np.allclose(p_inf_41, p_inf_42)

True

<p class="task" id="5"></p>

5\. Напишите функцию `generate_walk`, которая принимает на вход граф `G`, начальный узел `node` и генерирует случайное блуждание длины `walk_len`, начинающееся с этого узла. Сгенерируйте несколько реализаций (не меньше 1000) случайных блужданий длины 10 с началом в узле 7 и выясните, в каком узле случайные блуждания заканчиваются чаще всего. Выведите номер этого узла на экран.

- [ ] Проверено на семинаре

In [26]:
def generate_walk(G, node, walk_len):
    # ...
    return walk

In [45]:
def generate_walk(G, node, walk_len):
    A = nx.adjacency_matrix(G, weight='None').toarray()
    D = np.diag(list(dict(G.degree()).values()))
    P = np.linalg.inv(D) @ A
    p_0 = len(G.nodes())*[0]
    p_0[node]=1
    eps=0.00001
    i=1
    while np.linalg.norm(np.linalg.matrix_power(P.T, i) - (P.T)@np.linalg.matrix_power(P.T, i))>=eps:
        P=np.linalg.matrix_power(P.T, i)
        i+=1  
    P_inf=np.linalg.matrix_power(P.T, i)
    walk=np.argmax(P_inf.T, axis=1)
    
    
    return walk

In [46]:
generate_walk(G, 7, 10)

C:\Users\Elena\AppData\Local\Temp\ipykernel_5032\1906065867.py:2: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  A = nx.adjacency_matrix(G, weight='None').toarray()


array([33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33],
      dtype=int64)

In [47]:
for i in range(1000):
    print(generate_walk(G, 7, 10))

C:\Users\Elena\AppData\Local\Temp\ipykernel_5032\1906065867.py:2: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  A = nx.adjacency_matrix(G, weight='None').toarray()


[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 

[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 

[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33
 33 33 33 33 33 33 33 33 33 33]
[33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 